[package]
name = "standard_paths"
description = "A port of QStandardPaths class which provides methods for accessing system standard paths."
version = "0.0.1"
authors = ["Petr Tsymbarovich <petr@tsymbarovich.ru>"]
repository = "https://github.com/mentaljam/standard_paths"
keywords = ["system", "standard", "paths"]
categories = ["filesystem"]
license = "MIT"

[target.'cfg(unix)'.dependencies]
users = "0.5.0"
