[package]
name = "standard_paths"
description = "A port of QStandardPaths class which provides methods for accessing standard paths on the local filesystem (config, cache, user directories and etc.)."
version = "0.4.2"
authors = ["Petr Tsymbarovich <petr@tsymbarovich.ru>"]
repository = "https://github.com/mentaljam/standard_paths"
documentation = "https://docs.rs/standard_paths"
keywords = ["standard", "paths", "location", "directory", "storage"]
categories = ["filesystem"]
license = "MIT"
readme = "README.md"

[target.'cfg(unix)'.dependencies]
users = "0.5.0"

[target.'cfg(windows)'.dependencies]
# winapi = { features = ["shlobj", "combaseapi", "winbase"], git = "https://github.com/retep998/winapi-rs", rev = "d51e532" }
winapi = "0.2"
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
kernel32-sys = "0.2.1"

[dev_dependencies]
argparse = "0.2.1"
