[package]
name = "standard_paths"
description = "A port of QStandardPaths class which provides methods for accessing system standard paths."
version = "0.1.0"
authors = ["Petr Tsymbarovich <petr@tsymbarovich.ru>"]
repository = "https://github.com/mentaljam/standard_paths"
keywords = ["system", "standard", "paths"]
categories = ["filesystem"]
license = "MIT"
readme = "README.md"

[target.'cfg(unix)'.dependencies]
users = "0.5.0"

[target.'cfg(windows)'.dependencies]
winapi = { features = ["shlobj", "combaseapi"], git = "https://github.com/retep998/winapi-rs" }
