[package]
name = "standard_paths"
description = "A port of QStandardPaths class which provides methods for accessing system standard paths."
version = "0.3.1"
authors = ["Petr Tsymbarovich <petr@tsymbarovich.ru>"]
repository = "https://github.com/mentaljam/standard_paths"
documentation = "https://mentaljam.github.io/standard_paths/standard_paths/"
keywords = ["system", "standard", "paths"]
categories = ["filesystem"]
license = "MIT"
readme = "README.md"

[target.'cfg(unix)'.dependencies]
users = "0.5.0"

[target.'cfg(windows)'.dependencies]
# winapi = { features = ["shlobj", "combaseapi", "winbase"], git = "https://github.com/retep998/winapi-rs", rev = "d51e532" }
winapi = "0.2"
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
kernel32-sys = "0.2.1"

[dev_dependencies]
argparse = "0.2.1"
